import React from "react";
import Head from "next/head";
import Footer from "/components/footer";
import NavBar from "/components/NavBar";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Christopher | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div>{children}</div>

      <footer>
        <Footer>
          <Footer.item title="MAIL ME">
            <a href="mailto: christopherx10x@gmail.com">
              christopherx10x@gmail.com
            </a>
          </Footer.item>
          <Footer.item title="CHAT">
            <a href="https://wa.me/523312436505">WhatsApp</a>
          </Footer.item>
        </Footer>
        <div style={{ textAlign: "center", fontSize: "0.8rem" }}>
          <p>
            Designed with <span style={{ color: "red" }}>♥</span> by Chris
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Layout;
