import Head from "next/head";
import NavBar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Logo from "../public/me.png";
import Text from "../components/text";
import Footer from "../components/footer";
import Skills from "../components/skills";
import Projects from "../components/projects";
import Journey from "../components/journey";

export default function Main() {
  return (
    <div>
      <Head>
        <title>Christopher | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main>
        <div className={styles.container}>
          <div className={styles.bar} />
          <section className={styles.start_section}>
            <div>
              <div className={styles.start_title_container}>
                <Text.title>Christopher Larios</Text.title>
                <Text.subtitle>
                  Software Engineer | Car enthusiast | Coffee Lover
                </Text.subtitle>
              </div>
              <div className={styles.start_content_container}>
                <Text>
                  Hey there, this is Chris. I am a software engineer who love{" "}
                  <br />
                  work with React, NodeJs and MoongoDB.
                </Text>
              </div>
            </div>

            <div className={styles.img_container}>
              <Image
                src={Logo}
                alt="Picture of the author"
                width={200}
                height={200}
              />
            </div>
          </section>
          <div className={styles.bar} />
          <section className={styles.skills_section} id="skills">
            <div>
              <Text.title>Skills</Text.title>
              <Text>
                I've worked with multiple technologies as a developer to develop
                & maintain my own and external projects.
              </Text>
            </div>
            <div>
              <Skills>
                <Skills.item title="React" />
                <Skills.item title="Typescript" />
                <Skills.item title="Javascript" />
                <Skills.item title="MongoDB" />
                <Skills.item title="NodeJS" />
                <Skills.item title="React Native" />
                <Skills.item title="Kotlin" />
                <Skills.item title="Git" />
                <Skills.item title="NextJS" />
                <Skills.item title="CSS" />
              </Skills>
            </div>
          </section>
          <div className={styles.bar} />
          <section className={styles.projects_section} id="projects">
            <div>
              <Text.title>Projects</Text.title>
              <Text>
                I've worked with multiple projects as a developer like:
              </Text>
            </div>
            <div>
              <Projects>
                <Projects.item
                  title="My Portafolio"
                  subtitle="This is my own portafolio website"
                  repoTitle="iChris96/my-portafolio"
                  repoUrl="https://github.com/iChris96/my-portafolio"
                  techArray={["React", "NextJS", "Javascript"]}
                >
                  This was my personal portfolio website that has all my work
                  and project experience, including my resume. It used to be my
                  main portfolio before deploying this current portfolio.
                </Projects.item>
                <Projects.item
                  title="MetroSmart Server"
                  subtitle="Route recommendation system based in prediction
                  of influx of people in metro stations"
                  techArray={["NodeJS", "Typescript", "MongoDB"]}
                  repoTitle="iChris96/MetroSmart_Backend"
                  repoUrl="https://github.com/iChris96/MetroSmart_Backend/tree/master"
                >
                  This is the description
                </Projects.item>
                <Projects.item
                  title="MetroSmart App"
                  subtitle="Android with kotlin app"
                  repoTitle="iChris96/MetroSmart_Android"
                  repoUrl="https://github.com/iChris96/MetroSmart_Android/tree/develop"
                  techArray={["Android", "Kotlin"]}
                >
                  this is a very large description
                </Projects.item>
                <Projects.item
                  title="Movies App"
                  subtitle="NodeJS & Typescript app "
                  repoTitle="iChris96/movies-app"
                  repoUrl="https://github.com/iChris96/movies-app/tree/feature/auth"
                  techArray={["NodeJS", "Typescript", "MYSQL"]}
                >
                  this is a very large description
                </Projects.item>
              </Projects>
            </div>
          </section>
          <div className={styles.bar} />
          <section className={styles.journey_section} id="journey">
            <div>
              <Text.title>My Journey</Text.title>
              <Text>
                In my journey to date, I have learned a great deal about
                development and life in general.
              </Text>
            </div>
            <div>
              <Journey>
                <Journey.item year="2016" title="Uni">
                  Started my journey as a computer engineer student.
                </Journey.item>
                <Journey.item year="2019">
                  Got an intership as android developer at Bosch Company.
                </Journey.item>
                <Journey.item year="2020">
                  End my journey as Computer Science student.
                </Journey.item>
                <Journey.item year="2020">
                  Started my journey as a full time software developer at Bosch
                  Company.
                </Journey.item>
                <Journey.item year="2021">
                  Started a new journey as software developer at Wizeline.
                </Journey.item>
              </Journey>
            </div>
          </section>
        </div>
      </main>

      <footer>
        <Footer>
          <Footer.item title="MAIL ME">
            <a href="mailto: christopherx10x@gmail.com">
              christopherx10x@gmail.com
            </a>
          </Footer.item>
          <Footer.item title="CHAT">
            <a href="https://wa.me/523312436505">WhatsApp</a>
          </Footer.item>
        </Footer>
        <div style={{ textAlign: "center" }}>
          <p>
            Designed with <span style={{ color: "red" }}>♥</span> by Chris
          </p>
        </div>
      </footer>
    </div>
  );
}
