import Head from "next/head";
import NavBar from "../components/navbar";
import styles from "../styles/Home.module.css";

export default function Main() {
  return (
    <div>
      <Head>
        <title>Christopher | Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main>
        <div className={styles.container}>
          <section>
            <div>
              <h1 className={styles.title}>Christopher Larios</h1>
              <p className={styles.subtitle}>
                Software Engineer | Car enthusiast | Coffee Lover
              </p>
            </div>
            <div>
              <p>
                this is a text
                loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem
              </p>
            </div>
          </section>
        </div>
      </main>
      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}
